services:
  fastapi_service:
    build:
      context: ./api/fastapi_service
    container_name: fastapi_service
    ports:
      - "8000:8000"
    entrypoint: ./wait-for-it.sh postgres_service:5432 -- uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql://postgres:123@postgres_service:5432/pythondb
    depends_on:
      - postgres_service
    networks:
      - net

  web_service:
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - fastapi_service
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - net

  postgres_service:
    build:
      context: ./db
    container_name: postgres_service
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - net
volumes:
  db_data:
networks:
  net: