# roles/db/tasks/main.yml
- name: Ensure Docker is installed
  apt:
    name: docker-ce
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create a network
  docker_network:
    name: "{{ docker_network_name }}"
  when: docker_network.exists == false
  become: true

- name: Run PostgreSQL container
  docker_container:
    name: "{{postgres_container_name}}"
    image: "{{ postgres_image_name }}:{{ postgres_image_tag }}"
    restart_policy: unless-stopped
    env:
      POSTGRES_DB: "{{env_POSTGRES_USER}}"
      POSTGRES_USER: "{{env_POSTGRES_DB}}"
      POSTGRES_PASSWORD: "{{env_POSTGRES_PASS}}"
    networks:
      - name: "{{ docker_network_name }}"
    ports: "{{postgres_ports}}"
    volumes:
      - name: pgdata
        source: /var/lib/postgresql/data
        state: present
        driver: local
  tags: docker
  become: true
