- name: Check docker network exists
  docker_network_info:
    name:  "{{ docker_network_name }}"
  register: docker_network
  become: true

- name: Create a network
  docker_network:
    name:  "{{ docker_network_name }}"
  when: docker_network.exists == false
  become: true

- name: Run React container
  docker_container:
    name: "{{ web_container_name }}"
    image: "{{ web_image_name }}:{{ web_image_tag }}"
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network_name }}"
    ports: "{{ web_ports }}"
    env:
      REACT_APP_API_URL: http://localhost:8000/
  tags: docker
  become: true

