---
- name: Setup Docker
  hosts: all
  become: true
  gather_facts: true

  roles:
    - common

- name: Setup  services 
  hosts: all
  become: true
  gather_facts: true

  roles:
    - web
    - db
    - api
